### PR TITLE
Cleaning files

### PR DESCRIPTION
**Pull request by JnxF**
Clean files and correct python package usage

### CODE REVIEW

**Comment by andersfischernielsen** [comment]
If I understand these commits correctly, this will remove 2/3 of the checkers currently in the repo. Is that correct? I like polishing off the launch checker, but removing the other ones seems like a waste of previous work :)

**Comment by andersfischernielsen** [comment]
Just saw this PR now, that's why I'm commenting

**Comment by JnxF** [comment]
I messed around with branches. This wasn't meant to be pushed here, but in the rosin repository. Sorry :)

**Comment by andersfischernielsen** [comment]
All good!

**Pull request closed without merging**
